-- CreateEnum
CREATE TYPE "ArtworkTechnique" AS ENUM ('OIL', 'ACRYLIC', 'WATERCOLOR', 'GOUACHE', 'INK', 'MIXED_MEDIA', 'DIGITAL_PAINTING', 'PASTEL', 'PENCIL', 'CHARCOAL', 'PRINT', 'SPRAY_PAINT', 'COLLAGE', 'OTHER');

-- CreateEnum
CREATE TYPE "ArtworkStyle" AS ENUM ('REALISM', 'ABSTRACT', 'EXPRESSIONISM', 'IMPRESSIONISM', 'MINIMALISM', 'SURREALISM', 'POP_ART', 'CUBISM', 'CONTEMPORARY', 'STREET_ART', 'FIGURATIVE', 'CONCEPTUAL', 'MODERN', 'OTHER');

-- CreateEnum
CREATE TYPE "ArtworkMotive" AS ENUM ('PORTRAIT', 'LANDSCAPE', 'STILL_LIFE', 'ANIMALS', 'FIGURE', 'CITYSCAPE', 'NATURE', 'RELIGIOUS_MYTHOLOGICAL', 'FANTASY_SCI_FI', 'GEOMETRIC', 'TYPOGRAPHY', 'SOCIAL_POLITICAL', 'OTHER');

-- CreateEnum
CREATE TYPE "ArtworkOrientation" AS ENUM ('PORTRAIT', 'LANDSCAPE', 'SQUARE', 'PANORAMIC');

-- CreateEnum
CREATE TYPE "ArtworkStandardSize" AS ENUM ('SIZE_30x40', 'SIZE_40x50', 'SIZE_50x70', 'SIZE_60x80', 'SIZE_70x100', 'A4_21x29_7', 'A3_29_7x42', 'A2_42x59_4', 'CUSTOM');

-- AlterTable
ALTER TABLE "Artwork" ADD COLUMN     "framed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "motive" "ArtworkMotive",
ADD COLUMN     "orientation" "ArtworkOrientation",
ADD COLUMN     "size" "ArtworkStandardSize",
ADD COLUMN     "style" "ArtworkStyle",
ADD COLUMN     "technique" "ArtworkTechnique";
